FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Blog-Website

Sample APIs for Experiments

## Sample Twitter Bot  [/sk-solutions/twitter-bot/top-question]

### Get Top Questions of Day [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "time_stamp": "2015-08-05T08:40:51.620Z",
                "user": "sk_solutions",
                "vote_count": 300
                
            }Demo
        ]