FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Blog-Website
actual URLhttp://private-4d97a-sksolutions.apiary-mock.com
Sample APIs for Experiments

## Twitter Bot  [/sk-solutions/twitter-bot/top-question]

### Top Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "time_stamp": "2015-08-05T08:42:51.620Z",
                "user": "sk_solutions",
                "vote_count": 300
                
            }
        ]
        
        
## Simple Post endpoint   [/post-here/please]

### Post Here [POST]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "time_stamp": "2015-08-05T08:42:51.620Z",
                "user": "sk_solutions",
                "vote_count": 300
                
            }
        ]
        
        
        
        
## Call Butler    [/twilio/call-butler]

### Call Butler [POST]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "time_stamp"ed: "2015-08-05T08:42:51.620Z",
        
                
            }
        ]
        
        
        
        
        
## WebSite API     [/stepank/blog]

### WebSite API [GET]

+ Response 200 (application/json)

        [
            {
                "blog": "is this the first Post?",
                "article": "Blog Post One",
        
                
            }
        ]
        
        
        
        

## Simple XML endpoint   [/xml-endpoint/twilio.xml]
### Twilio api Response that you want user to get  [POST]

+ Response 200 (text/xml)
    + Body

            <?xml version="1.0"?>
            <Response>
                <Say voice="alice">Get to the Choppa and ShutDown the VPN! Hey Google Play slush cup on shield TV</Say>
            <Play>http://demo.twilio.com/docs/classic.mp3</Play>
            </Response>